version: '3.4'

services:
  sched:
    image: sched
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  
volumes:
  db: